"""
    pygments.lexers.uwsc
    ~~~~~~~~~~~~~~~~~~~~

    Lexer for the UWSC language

    :copyright: Copyright 2012 by the Youichi Kato, see AUTHORS
    :license: BSD, see LICENSE for details.
"""

import re

from pygments.lexer import Lexer, RegexLexer, include, bygroups, using, \
     this, do_insertions
from pygments.token import Error, Punctuation, Literal, Token, \
     Text, Comment, Operator, Keyword, Name, String, Number, Generic

class UWSCLexer(RegexLexer):
    name = 'UWSC'
    aliases = ['uwsc']
    filenames = ['*.uws', '*.uwsc', '*.UWS', '*.UWSC']
    mimetypes = ['text/x-uwsc', 'text/plain']

    flags = re.IGNORECASE

    keywords = [
        'DIM',
        'PUBLIC',
        'CONST',
        'IF',
        'THEN',
        'ELSE',
        'IFB',
        'ELSEIF',
        'ENDIF',
        'SELECT',
        'CASE',
        'DEFAULT',
        'SELEND',
        'FOR',
        'NEXT',
        'TO',
        'STEP',
        'WHILE',
        'WEND',
        'REPEAT',
        'UNTIL',
        'CALL',
        'BREAK',
        'CONTINUE',
        'EXIT',
        'PRINT',
        'AND',
        'OR',
        'XOR',
        'MOD',
        'PROCEDURE',
        'FUNCTION',
        'FEND',
        'RESULT',
        'VAR',
        'DEF_DLL',
        'OPTIN',
        'THREAD',
        'CLASS',
        'ENDCLASS',
        'THIS',
        'GLOBAL',
        'WITH',
        'ENDWITH',
        'TEXBLOCK',
        'ENDTEXTBLOCK',
        'HASHTBL',
        'TRY',
        'ENDTRY',
        'EXCEPT',
        'FINALLY',
    ]

    functions = [
        'GETID',
        'CLKITEM',
        'CHKBTN',
        'CTRLWIN',
        'SENDSTR',
        'GETSTR',
        'GETITEM',
        'GETSLCTLIST',
        'SETSLIDER',
        'GETSLIDER',
        'SCKEY',
        'GETALLWIN',
        'STATUS',
        'MOUSEORG',
        'PEEKCOLOR',
        'CHKIMG',
        'SAVEIMG',
        'MUSCUR',
        'POSACC',

        'SENDSTR',
        'GETSTR',
        'SETSLIDER',
        'GETALLWIN',
        'STATUS',
        'FUKIDASI',
        'CHKBTN',
        'MOUSEORG',
        'PEEKCOLOR',
        'CHKIMG',
        'SAVEIMG',
        'GETITEM',
        'MUSCUR',

        'INPUT',
        'MSGBOX',
        'SLCTBOX',
        'POPUPMENU',
        'FUKIDASI',
        'STOPFORM',
        'LOGPRINT',

        'EXEC',
        'SLEEP',
        'DOSCMD',
        'POWERSHELL',
        'SOUND',
        'GETTIME',
        'POFF',
        'KINDOFOS',
        'CPUUSERATE',
        'GETKEYSTATE',
        'SETHOTKEY',
        'LOCKHARD',
        'EVAL',

        'GETCTLHND',
        'IDTOHND',
        'HNDTOID',
        'VARTYPE',

        'MMV',
        'BTN',
        'KBD',
        'ACW',

        'COPY',
        'POS',
        'LENGTH',
        'CHKNUM',
        'VAL',
        'REPLACE',
        'TRIM',
        'FORMAT',
        'CHR',
        'ASC',
        'ISUNICODE',
        'STRCONV',
        'TOKEN',
        'BETWEENSTR',
        'COPYB',
        'LENGTHB',
        'POSB',
        'CHRB',
        'ASCB',

        'RESIZE',
        'SETCLEAR',
        'SETCLEAR',
        'SHIFTARRAY',
        'CALCARRAY',
        'SPLIT',
        'JOIN',
        'SLICE',
        'QSORT',

        'FOPEN',
        'FGET',
        'FPUT',
        'FDELLINE',
        'FCLOSE',
        'GETDIR',
        'DROPFILE',

        'READINI',
        'WRITEINI',
        'DELETEINI',

        'CREATEOLEOBJ',
        'GETACTIVEOLEOBJ',
        'GETOLEITEM',
        'OLEEVENT',
        'COM_ERR_IGN',
        'COM_ERR_RET',
        'SAFEARRAY',

        'SPEAK',
        'RECOSTATE',
        'DICTATE',

        'IEGETDATA',
        'IESETDATA',
        'IEGETSRC',
        'IESETSRC',
        'IELINK',
        'ENCODE',
        'DECODE',

        'CREATEFORM',
        'GETFORMDATA',
        'SETFORMDATA',

        'XLOPEN',
        'XLCLOSE',
        'XLACTIVATE',
        'XLSHEET',
        'XLGETDATA',
        'XLSETDATA',

        'RANDOM',
        'ABS',
        'ZCUT',
        'INT',
        'ROUND',
        'SQRT',
        'POWER',
        'EXP',
        'LN',
        'LOGN',
        'SIN',
        'COS',
        'TAN',
        'ARCSIN',
        'ARCCOS',
        'ARCTAN',

        'PARAM_STR',
        'ALL_WIN_ID',
        'ALL_ITEM_LIST',
        'GETDIR_FILES',
        'ALL_OLE_ITEM',
        'EVENT_PRM',

        'GET_WIN_DIR',
        'GET_SYS_DIR',
        'GET_CUR_DIR',
        'GET_APPDATA_DIR',
        'GET_UWSC_DIR',
        'GET_UWSC_VER',
        'GET_UWSC_NAME',

        'COM_ERR_FLG',
        'G_ING_X',
        'G_IMG_Y',

        'G_SCREEN_W',
        'G_SCREEN_H',
        'G_SCREEN_C',

        'G_MOUSE_X',
        'G_MOUSE_Y',

        'TRY_ERRMSG',
        'TRY_ERRLINE',
        'HOTKEY_VK',
        'HOYKEY_MOD',

        'G_TIME_YY',
        'G_TIME_MM',
        'G_TIME_DD',
        'G_TIME_HH',
        'G_TIME_NN',
        'G_TIME_SS',
        'G_TIME_ZZ',
        'G_TIME_WW',
        'G_TIME_YY2',
        'G_TIME_MM2',
        'G_TIME_DD2',
        'G_TIME_HH2',
        'G_TIME_NN2',
        'G_TIME_SS2',
        'G_TIME_ZZ2',
        'G_TIME_YY4',

    ]

    consts = [
        'TRUE',
        'FALSE',
        'NULL',
        'EMPTY',
        'NOTHING',
        'ERR_VALUE',
        'GET_SLIDER',
        'GET_MENU_HND',
        'GET_SYSMENU_HND',
        'ACTIVATE',
        'CLOSE',
        'CLOSE2',
        'HIDE',
        'SHOW',
        'MIN',
        'MAX',
        'NORMAL',
        'TOPMOST',
        'NOTOPMOST',

        'CLICK',
        'DOWN',
        'UP',
        'LEFT',
        'RIGHT',
        'MIDDLE',
        'WHEEL',

        'F_READ',
        'F_WRITE',
        'F_EXISTS',
        'F_LINECOUNT',
        'F_ALLTEXT',

        'BTN_YES',
        'BTN_NO',
        'BTN_OK',
        'BTN_CANCEL',
        'BTN_ABORT',
        'BTN_RETRY',
        'BTN_IGNORE',

        'CLK_BTN',
        'CLK_LIST',
        'CLK_TAB',
        'CLK_MENU',
        'CLK_TREEVEW',
        'CLK_LSTVEW',
        'CLK_TOOLBAR',
        'CLK_ACC',
        'CLK_SHORT',
        'CLK_BACK',
        'CLK_MUSMOVE',
        'CLK_RIGHTCLK',
        'CLK_LEFTCLK',
        'CLK_DBLCLK',
        'CLK_FROMLAST',
        'CLK_CONTINUE',

        'ITM_BTN',
        'ITM_LIST',
        'ITM_TAB',
        'ITM_MENU',
        'ITM_TREEVEW',
        'ITM_LSTVEW',
        'ITM_EDIT',
        'ITM_STATIC',
        'ITM_STATUSBAR',
        'ITM_TOOLBAR',
        'ITM_ACCCLK',
        'ITM_ACCTXT',
        'ITM_BACK',

        'ST_TITLE',
        'ST_CLASS',
        'ST_X',
        'ST_Y',
        'ST_WIDTH',
        'ST_HEIGHT',
        'ST_CLX',
        'ST_CLY',
        'ST_CLWIDTH',
        'ST_CLHEIGHT',
        'ST_PARENT',
        'ST_ICON',
        'ST_VISIBLE',
        'ST_ACTIVE',
        'ST_BUSY',
        'ST_PATH',
        'ST_PROCESS',
        'ST_WIN64',

        'SLCT_BTN',
        'SLCT_CHK',
        'SLCT_RDO',
        'SLCT_CMB',
        'SLCT_LST',
        'SLCT_STR',
        'SLCT_NUM',

        'CUR_APPSTARTING',
        'CUR_ARROW',
        'CUR_CROSS',
        'CUR_HAND',
        'CUR_HELP',
        'CUR_IBEAM',
        'CUR_NO',
        'CUR_SIZEALL',
        'CUR_SIZENESW',
        'CUR_SIZENS',
        'CUR_SIZENWSE',
        'CUR_SIZEWE',
        'CUR_UPARROW',
        'CUR_WAIT',

        'ACC_ACC',
        'ACC_API',
        'ACC_NAME',
        'ACC_VALUE',
        'ACC_ROLE',
        'ACC_STATE',
        'ACC_DESCRIPTION',
        'ACC_LOCATION',
        'ACC_BACK',

        'P_POWEROFF',
        'P_LOGOFF',
        'P_REBOOT',
        'P_SUSPEND',
        'P_SUSPEND2',
        'P_MONIPOWER',
        'P_MONIPOWER2',
        'P_MONIPOWER3',
        'P_SCREENSAVE',
        'P_UWSC_REEXEC',
        'P_FORCE',

        'GET_ACTIVE_WIN',
        'GET_FROMPOINT_WIN',
        'GET_FROMPOINT_OBJ',
        'GET_THISUWSC_WIN',
        'GET_LOGPRINT_WIN',
        'GET_FUKIDASI_WIN',
        'GET_FORM_WIN',
        'GET_SCHEDULE_WIN',

        'TGL_IME',
        'TGL_NUMLOCK',
        'TGL_CAPSLOCK',
        'TGL_SCROLLLOCK',
        'TGL_KANALOCK',

        'SC_LOWERCASE',
        'SC_UPPERCASE',
        'SC_HIRAGANA',
        'SC_KATAKANA',
        'SC_HALFWIDTH',
        'SC_FULLWIDTH',

        'FOM_NOICON',
        'FOM_MINIMIZE',
        'FOM_MAXIMIZE',
        'FOM_NOHIDE',
        'FOM_NOSUBMIT',
        'FOM_NORESIZE',
        'FOM_NOLUNA',
        'FOM_BROWSER',

        'CODE_URL',
        'CODE_UTF8',
        'CODE_BYTEARRAY',
        'CODE_BYTEARRAYW',

        'CALC_ADD',
        'CALC_MIN',
        'CALC_MAX',
        'CALC_AVR',

        'ALL_IMG_X',
        'ALL_IMG_Y',
        'IMG_MSK_BGR1',
        'IMG_MSK_BGR2',
        'IMG_MSK_BGR3',
        'IMG_MSK_BGR4',
        'IMG_MSK_B1',
        'IMG_MSK_B2',
        'IMG_MSK_B3',
        'IMG_MSK_B4',
        'IMG_MSK_G1',
        'IMG_MSK_G2',
        'IMG_MSK_G3',
        'IMG_MSK_G4',
        'IMG_MSK_R1',
        'IMG_MSK_R2',
        'IMG_MSK_R3',
        'IMG_MSK_R4',

        'MOD_ALT',
        'MOD_CONTROL',
        'MOD_SHIFT',
        'MOD_WIN',

        'SLD_POS',
        'SLD_MIN',
        'SLD_MAX',
        'SLD_PAGE',
        'SLD_BAR',
        'SLD_X',
        'SLD_Y',

        'VK_START',
        'VK_WIN',
        'VK_ALT',
        'VK_CTRL',
        'VK_RCTRL',
        'VK_ESC',
        'VK_BACK',
        'VK_TAB',
        'VK_CLEAR',
        'VK_RETURN',
        'VK_RRETURN',
        'VK_SHIFT',
        'VK_RSHIFT',
        'VK_CONTROL',
        'VK_MENU',
        'VK_PAUSE',
        'VK_CAPITAL',
        'VK_KANA',
        'VK_FINAL',
        'VK_KANJI',
        'VK_CONVERT',
        'VK_NONCONVERT',
        'VK_ACCEPT',
        'VK_MODECHANGE',
        'VK_ESCAPE',
        'VK_SPACE',
        'VK_PRIOR',
        'VK_NEXT',
        'VK_END',
        'VK_HOME',
        'VK_LEFT',
        'VK_UP',
        'VK_RIGHT',
        'VK_DOWN',
        'VK_SELECT',
        'VK_PRINT',
        'VK_EXECUTE',
        'VK_SNAPSHOT',
        'VK_INSERT',
        'VK_DELETE',
        'VK_HELP',
        'VK_APPS',
        'VK_MULTIPLY',
        'VK_ADD',
        'VK_SEPARATOR',
        'VK_SUBTRACT',
        'VK_DECIMAL',
        'VK_DIVIDE',
        'VK_NUMPAD0',
        'VK_NUMPAD1',
        'VK_NUMPAD2',
        'VK_NUMPAD3',
        'VK_NUMPAD4',
        'VK_NUMPAD5',
        'VK_NUMPAD6',
        'VK_NUMPAD7',
        'VK_NUMPAD8',
        'VK_NUMPAD9',
        'VK_F1',
        'VK_F2',
        'VK_F3',
        'VK_F4',
        'VK_F5',
        'VK_F6',
        'VK_F7',
        'VK_F8',
        'VK_F9',
        'VK_F10',
        'VK_F11',
        'VK_F12',
        'VK_NUMLOCK',
        'VK_SCROLL',
        'VK_SLEEP',

        'VK_BROWSER_BACK',
        'VK_BROWSER_FORWARD',
        'VK_BROWSER_REFRESH',
        'VK_BROWSER_STOP',
        'VK_BROWSER_SEARCH', 
        'VK_BROWSER_FAVORITES',
        'VK_BROWSER_HOME',
        'VK_VOLUME_MUTE',
        'VK_VOLUME_DOWN',
        'VK_VOLUME_UP',
        'VK_MEDIA_NEXT_TRACK',
        'VK_MEDIA_PREV_TRACK',
        'VK_MEDIA_STOP',
        'VK_MEDIA_PLAY_PAUSE',
        'VK_LAUNCH_MEDIA_SELECT',
        'VK_LAUNCH_MAIL',
        'VK_LAUNCH_APP1',
        'VK_LAUNCH_APP2 ',
        'VK_OEM_PLUS',
        'VK_OEM_COMMA',
        'VK_OEM_MINUS',
        'VK_OEM_PERIOD',
        'VK_OEM_1',
        'VK_OEM_2',
        'VK_OEM_3',
        'VK_OEM_4',
        'VK_OEM_5',
        'VK_OEM_6',
        'VK_OEM_7',
        'VK_OEM_8',
        'VK_OEM_RESET',
        'VK_OEM_JUMP',
        'VK_OEM_PA1',
        'VK_OEM_PA2',
        'VK_OEM_PA3',
    ]

    tokens = {
        'comments': [
            (r'//.*?\n', Comment.Single),
        ],

        'heredocument': [
            (r'(\ |\t)*TEXTBLOCK([^"])*ENDTEXTBLOCK', String.Double),
        ],
        
        'keywords': [
            ('(' + '|'.join(keywords) + r')\b', Keyword.Reserved),
            ('(' + '|'.join(consts) + r')\b', Keyword.Constant),
        ],

        'functions': [
            ('(' + '|'.join(functions) + r')\b', Name.Builtin),
         ],

        'slashstartsregex': [
            include('comments'),
            (r'/(\\.|[^[/\\\n]|\[(\\.|[^\]\\\n])*])+/'
             r'([gim]+\b|\B)', String.Regex, '#pop'),
            (r'(?=/)', Text, ('#pop', 'badregex')),
            (r'', Text, '#pop')
        ],
        'badregex': [
            (r'\n', Text, '#pop')
        ],

        'root': [
            include('comments'),
            include('heredocument'),

            (r'=|<>|<|<=|>|>=', Operator, 'slashstartsregex'),
            (r'\+|-|\*|/', Operator, 'slashstartsregex'),

            (r'[{(\[;,]', Punctuation, 'slashstartsregex'),
            (r'[})\].]', Punctuation),

            include('keywords'),
            include('functions'),

            (r'\ |\t', Text.Whitespace),
            (r'[$a-zA-Z_][a-zA-Z0-9_]*', Name.Other),
            (r'[-]?[0-9][0-9]*\.[0-9]+([eE][0-9]+)?[fd]?', Number.Float),
            (r'[-]?[0-9]+', Number.Integer),
            (r'"([^"])*"', String.Double),
        ],

    }
